import Foundation

// The bundled catalogue: one JSON file per country plus a countries.json
// manifest, generated by tools/build_index.py.
//
// Split per country on purpose. The full catalogue is ~2.8 MB of JSON and
// NSJSONSerialization on an A5 takes seconds to chew through that in one go,
// with a matching memory spike. Loading only the country the user opened
// keeps the cost proportional to what is on screen.

struct Country {
    let code: String
    let name: String
    let count: Int
}

struct Channel {
    let name: String
    let url: String
    let quality: String
    let categories: [String]
    let logo: String?
    let userAgent: String?
    let referrer: String?

    // Handed to LocalStreamProxy.start — some origins 403 without these.
    var headers: [String: String] {
        var h: [String: String] = [:]
        if let ua = userAgent { h["User-Agent"] = ua }
        if let rf = referrer { h["Referer"] = rf }
        return h
    }

    // The short keys match the on-disk format; favourites are persisted in
    // the same shape so no separate encoding is needed.
    init?(json: [String: Any]) {
        guard let n = json["n"] as? String, let u = json["u"] as? String else { return nil }
        name = n
        url = u
        quality = (json["q"] as? String) ?? ""
        categories = (json["g"] as? [String]) ?? []
        logo = json["l"] as? String
        userAgent = json["ua"] as? String
        referrer = json["rf"] as? String
    }

    var json: [String: Any] {
        var d: [String: Any] = ["n": name, "u": url, "q": quality, "g": categories]
        if let l = logo { d["l"] = l }
        if let ua = userAgent { d["ua"] = ua }
        if let rf = referrer { d["rf"] = rf }
        return d
    }
}

final class ChannelIndex {
    static let shared = ChannelIndex()

    private let queue = DispatchQueue(label: "tvold.index")
    private var countryCache: [Country]?
    // Only the most recently opened country is kept — the largest single file
    // (United States) parses to several MB of Foundation objects.
    private var loadedCode: String?
    private var loadedChannels: [Channel] = []

    private var dir: String {
        return (Bundle.main.resourcePath ?? "") + "/index"
    }

    // countries.json is a few KB; parsing it on the main thread is cheaper
    // than the hop to a background queue and back.
    func countries() -> [Country] {
        if let c = countryCache { return c }
        var result: [Country] = []
        if let data = NSData(contentsOfFile: dir + "/countries.json") as Data?,
           let arr = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [[String: Any]] {
            for m in arr {
                guard let code = m["c"] as? String, let name = m["n"] as? String,
                      let count = m["k"] as? Int else { continue }
                result.append(Country(code: code, name: name, count: count))
            }
        } else {
            DebugLog.shared.log("Index", "countries.json missing or unparseable at \(dir)")
        }
        countryCache = result
        return result
    }

    func channels(for code: String, completion: @escaping ([Channel]) -> Void) {
        queue.async {
            if self.loadedCode == code {
                let cached = self.loadedChannels
                DispatchQueue.main.async { completion(cached) }
                return
            }
            let t0 = CFAbsoluteTimeGetCurrent()
            var result: [Channel] = []
            if let data = NSData(contentsOfFile: self.dir + "/\(code).json") as Data?,
               let arr = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [[String: Any]] {
                result.reserveCapacity(arr.count)
                for item in arr {
                    if let c = Channel(json: item) { result.append(c) }
                }
            } else {
                DebugLog.shared.log("Index", "\(code).json missing or unparseable")
            }
            let ms = Int((CFAbsoluteTimeGetCurrent() - t0) * 1000)
            DebugLog.shared.log("Index", "loaded \(code): \(result.count) channels in \(ms)ms")
            self.loadedCode = code
            self.loadedChannels = result
            DispatchQueue.main.async { completion(result) }
        }
    }
}
